//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDV
    {
        public int MaHDDV { get; set; }
        public int MaDV { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string TenDV { get; set; }
        public string LoaiDV { get; set; }
    }
}
